const colors = {
    white : '#ffffff',
    black : '#000000',
    grey_0 : '#d5d5d5',
    grey_1 : '#a6a6a6',
    red : '#e84118',
    blue : '#3679fe',
    green_1 : '#08D37A',
    orange : '#CFA636',
    orange_1 : '#F9DAB0',
    brown : 'brown',
};

export const theme = {
    background : colors.white,
    text : colors.black,
    label : colors.grey_1,
    inputPlaceholder : colors.grey_1,
    inputBorder : colors.grey_1,
    errorText : colors.red,
    buttonBackground : colors.blue,
    buttonTitle : colors.white,
    buttonUnfilledTitle : colors.green_1,
    logoBorder : colors.orange_1,
    buttonBackground : colors.green_1,
    buttonTitle : colors.white,
    headerTintColor:colors.black,
    tabActiveColor:colors.orange,
    tabInactiveColor:colors.grey_1,
}